app = "your-n8n-rag-app-name"  # Replace with your desired app name

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  N8N_ENCRYPTION_KEY = "your-secure-encryption-key-min-16-chars"
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  N8N_PROTOCOL = "https"

[http_service]
  internal_port = 5678
  force_https = true

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/healthz"